name: Build and Deploy Lambda

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      FUNCTION_NAME: BatchTransferFunction
      S3_BUCKET_NAME: batch-transfer-lambda-deployment
      AWS_REGION: eu-north-1

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies to package/
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r requirements.txt -t package
          cp batch_transfer_lambda.py solana_utils.py package/

      - name: Zip Lambda package
        run: |
          cd package
          zip -r9 ../batch_transfer_lambda.zip .

      - name: Upload zip to S3
        run: |
          aws s3 cp batch_transfer_lambda.zip s3://$S3_BUCKET_NAME/batch_transfer_lambda.zip --region $AWS_REGION

      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --s3-bucket $S3_BUCKET_NAME \
            --s3-key batch_transfer_lambda.zip \
            --region $AWS_REGION
