name: Build and Deploy Lambda

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      FUNCTION_NAME: BatchTransferFunction
      S3_BUCKET_NAME: batch-transfer-lambda-deployment
      AWS_REGION: eu-north-1

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install AWS CLI via pip
        run: |
          python -m pip install --upgrade pip
          pip install awscli

      - name: Install Lambda dependencies into package folder
        run: |
          pip install -r requirements.txt -t package
          cp batch_transfer_lambda.py solana_utils.py package/

      - name: Zip Lambda package
        run: |
          cd package
          zip -r9 ../batch_transfer_lambda.zip .

      - name: Upload zip to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp batch_transfer_lambda.zip s3://$S3_BUCKET_NAME/batch_transfer_lambda.zip --region $AWS_REGION

      - name: Update Lambda function code
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --s3-bucket $S3_BUCKET_NAME \
            --s3-key batch_transfer_lambda.zip \
            --region $AWS_REGION
